Error in `gzfile()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─base::readRDS(file.path(res.path, "out_unPruned.rds"))
 2.   └─base::gzfile(file, "rb")

Quitting from FigureYa308IHS.Rmd:208-221 [unnamed-chunk-5]
Execution halted
